pme: hardcode the includes for amplifier
- Fixes this error:
device/htc/pme/amplifier/audio_amplifier.c:27:10: fatal error: 'msm8974/platform.h' file not found

- AOSPA use another location so qcom-audio groups no longer exits